# Site settings
title: Your awesome title
email: admin@hdgem.com
description: > # this means to ignore newlines until "baseurl:"
  IT information, news, tutorials, examples, documentation, career
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pages.hdgem.com" # the base hostname & protocol for your site
twitter_username: i88ca
github_username:  i88ca

# Build settings
markdown: kramdown
